(function(){
if(window.__GJ_AUTH_V108_LOADED__)return;window.__GJ_AUTH_V108_LOADED__=true;
let sb=null,configurationError=null;
try{sb=window.GJ_CONFIG_API.createSupabaseClient()}catch(error){configurationError=error}
window.GJ_AUTH={sb,identitySb:sb,profile:null,isAdmin:false,workspaceUserId:null,impersonating:false,realUserId:null};window.GJ_WORKSPACE_ID=()=>GJ_AUTH.workspaceUserId||GJ_AUTH.profile?.id||null;
const REMEMBER_KEY='gj_login_remember_v1',SESSION_KEY='gj_app_open_session';
const saved=(()=>{try{return JSON.parse(localStorage.getItem(REMEMBER_KEY)||'null')}catch{return null}})();
const WORKSPACE_TABLES=new Set(['customers','planning','app_day_settings','app_absences','fixed_appointments','visit_history','visit_photos']);
function workspaceClient(raw,owner){
 const wrap=(builder,table,needsFilter=true)=>new Proxy(builder,{get(target,prop){
  if(prop==='then'){const q=needsFilter?target.eq('user_id',owner):target;return q.then.bind(q)}
  const value=target[prop];if(typeof value!=='function')return value;
  return (...args)=>{let filter=needsFilter;if(prop==='insert'||prop==='upsert'){const add=row=>({...row,user_id:owner});args[0]=Array.isArray(args[0])?args[0].map(add):add(args[0]);filter=false;if(prop==='upsert'&&table==='app_day_settings'&&args[1]?.onConflict==='datum')args[1]={...args[1],onConflict:'user_id,datum'}}const result=value.apply(target,args);return result&&typeof result.then==='function'?wrap(result,table,filter):result}
 }});
 return new Proxy(raw,{get(target,prop){if(prop==='from')return table=>{const b=target.from(table);return WORKSPACE_TABLES.has(table)?wrap(b,table,true):b};const value=target[prop];return typeof value==='function'?value.bind(target):value}})
}
const lang=localStorage.getItem('gj_app_language')||'nl',TX={nl:['Welkom','E-mailadres','Wachtwoord','E-mailadres onthouden','Inloggen','Wachtwoord vergeten','Alleen het e-mailadres wordt op dit apparaat onthouden. Het wachtwoord wordt nooit opgeslagen.'],en:['Welcome','Email address','Password','Remember email address','Sign in','Forgot password','Only the email address is remembered on this device. The password is never stored.'],de:['Willkommen','E-Mail-Adresse','Passwort','E-Mail-Adresse speichern','Anmelden','Passwort vergessen','Auf diesem Gerät wird nur die E-Mail-Adresse gespeichert. Das Passwort wird niemals gespeichert.']},x=TX[lang]||TX.nl;
document.head.insertAdjacentHTML('beforeend',`<style>#gjAuthGate{position:fixed;inset:0;z-index:999999;background:radial-gradient(circle at 50% 12%,#0a315a 0,#03152c 46%,#020a18 100%);display:flex;align-items:center;justify-content:center;padding:20px;font-family:Arial,sans-serif}#gjAuthCard{width:min(420px,100%);background:transparent;border:0;border-radius:0;padding:18px 8px;box-shadow:none}.gjLogo{display:block;width:min(152px,38vw);height:auto;aspect-ratio:1;object-fit:cover;border-radius:24px;margin:0 auto 12px;box-shadow:0 12px 30px #0008}.gjSub{text-align:center;color:#f8fafc;margin:0 0 20px;font-size:20px;font-weight:900}.gjField{display:grid;gap:6px;margin:11px 0;font-weight:800;color:#e8eef6}.gjField input{font:inherit;padding:12px;border:1px solid #aabbd0;border-radius:11px;background:rgba(255,255,255,.96);color:#102a43;box-shadow:0 4px 14px #0003}.gjRemember{display:flex;align-items:center;gap:8px;margin:10px 0;color:#dbe6f2;font-size:14px;font-weight:700}.gjRemember input{width:18px;height:18px}.gjBtn{width:100%;border:1px solid #8da5c0;border-radius:12px;padding:12px;font:inherit;font-weight:900;background:#2363a5;color:#fff;margin-top:8px;box-shadow:0 7px 18px #0004}.gjBtn.secondary{background:rgba(255,255,255,.1);color:#edf4fb;border-color:#7890aa;box-shadow:none}.gjMsg{min-height:22px;color:#ffb4ad;margin-top:10px;text-align:center;font-weight:700}.gjSecurity{font-size:11px;color:#aebed0;text-align:center;margin-top:8px}.gjUserBar{display:none!important}.gjAdminOnly,body:not(.gj-admin) .gjAdminOnly,body:not(.gj-admin) button.gjAdminOnly,body:not(.gj-admin) .menuPanel button.gjAdminOnly{display:none!important}body.gj-admin .gjAdminOnly{display:block!important}body.gj-admin button.gjAdminOnly{display:flex!important}body.gj-admin .menuPanel button.gjAdminOnly{display:grid!important}@media(max-height:700px){.gjLogo{width:min(126px,32vw);margin-bottom:8px}.gjSub{margin-bottom:12px}.gjField{margin:8px 0}}</style>`);
document.body.insertAdjacentHTML('beforeend',`<div id="gjAuthGate"><div id="gjAuthCard"><img src="assets/icons/icon-512.png?v=113800-login" class="gjLogo" alt="Planyx"><div class="gjSub">${x[0]}</div><label class="gjField">${x[1]}<input id="gjEmail" type="email" autocomplete="username"></label><label class="gjField">${x[2]}<input id="gjPassword" type="password" autocomplete="current-password"></label><label class="gjRemember"><input id="gjRemember" type="checkbox"> ${x[3]}</label><button id="gjLogin" class="gjBtn">${x[4]}</button><button id="gjReset" class="gjBtn secondary">${x[5]}</button><div id="gjMsg" class="gjMsg"></div><div class="gjSecurity">${x[6]}</div></div></div>`);
const emailEl=document.getElementById('gjEmail'),passwordEl=document.getElementById('gjPassword'),rememberEl=document.getElementById('gjRemember'),msg=t=>document.getElementById('gjMsg').textContent=t||'';
if(saved?.remember){emailEl.value=saved.email||'';rememberEl.checked=true;if(saved.password)localStorage.setItem(REMEMBER_KEY,JSON.stringify({remember:true,email:saved.email||''}))}
async function profileFor(user){let {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;const m=user.user_metadata||{};if(!data){const row={id:user.id,email:user.email,first_name:m.first_name||'',last_name:m.last_name||'',full_name:m.full_name||user.email,role:'user',is_active:true};const r=await sb.from('profiles').upsert(row).select().single();if(r.error)throw r.error;data=r.data}data.role=String(data.role).toLowerCase()==='admin'?'admin':'user';return data}
async function openApp(session){
 const p=await profileFor(session.user);if(p.is_active===false){await sb.auth.signOut();throw new Error('Dit account is uitgeschakeld.')}
 const roleCheck=await sb.rpc('is_app_admin');if(roleCheck.error)throw new Error('De centrale rolcontrole kon niet worden geladen. Voer eerst de v10.7 development-baseline en daarna de v10.8-DEV-SQL uit op het afzonderlijke testproject.');
 const isAdmin=roleCheck.data===true,requested=sessionStorage.getItem('gj_impersonate_user_v102');let wk=p.id,impersonating=false;
 if(isAdmin&&requested&&requested!==p.id){const target=await sb.from('profiles').select('id,is_active').eq('id',requested).maybeSingle();if(!target.error&&target.data&&target.data.is_active!==false){wk=target.data.id;impersonating=true}else sessionStorage.removeItem('gj_impersonate_user_v102')}
 if(!isAdmin&&requested)sessionStorage.removeItem('gj_impersonate_user_v102');
 sessionStorage.setItem('gj_authenticated_user_id',p.id);window.GJ_REAL_USER_ID=p.id;GJ_AUTH.profile=p;GJ_AUTH.isAdmin=isAdmin;GJ_AUTH.realUserId=p.id;GJ_AUTH.workspaceUserId=wk;GJ_AUTH.impersonating=impersonating;GJ_AUTH.identitySb=sb;
 const previousWorkspace=sessionStorage.getItem('gj_workspace_storage_id');GJ_AUTH.sb=workspaceClient(sb,wk);sessionStorage.setItem('gj_workspace_storage_id',wk);if(previousWorkspace!==wk){location.reload();return}
 document.body.classList.toggle('gj-admin',isAdmin);document.getElementById('gjAuthGate').style.display='none';window.dispatchEvent(new CustomEvent('gj-auth-ready',{detail:{profile:p,isAdmin,realUserId:p.id,workspaceUserId:wk,impersonating}}))
}
async function boot(){if(!sb){msg(configurationError?.message||'De developmentconfiguratie kon niet worden geladen.');return}const allowed=sessionStorage.getItem(SESSION_KEY)==='1',r=await sb.auth.getSession();if(allowed&&r.data.session){try{await openApp(r.data.session)}catch(e){msg(e.message)}}else if(r.data.session)await sb.auth.signOut()}
document.getElementById('gjLogin').onclick=async()=>{try{if(!sb)throw configurationError||new Error('Developmentconfiguratie ontbreekt.');msg('Bezig met inloggen...');const email=emailEl.value.trim(),password=passwordEl.value,r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(rememberEl.checked)localStorage.setItem(REMEMBER_KEY,JSON.stringify({remember:true,email}));else localStorage.removeItem(REMEMBER_KEY);passwordEl.value='';sessionStorage.setItem(SESSION_KEY,'1');await openApp(r.data.session)}catch(e){msg(e.message)}};
document.getElementById('gjReset').onclick=async()=>{try{if(!sb)throw configurationError||new Error('Developmentconfiguratie ontbreekt.');const email=emailEl.value.trim();if(!email)throw new Error('Vul eerst je e-mailadres in.');const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;msg('Herstellink is verstuurd.')}catch(e){msg(e.message)}};
if(sb)sb.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')window.dispatchEvent(new CustomEvent('gj-auth-signed-out'))});boot();
})();
/* Planning-GJsystems v10.7 */
