(function(){
if(window.__GJ_AUTH_V108_LOADED__)return;window.__GJ_AUTH_V108_LOADED__=true;
let sb=null,configurationError=null;
try{sb=window.GJ_CONFIG_API.createSupabaseClient()}catch(error){configurationError=error}
window.GJ_AUTH={sb,identitySb:sb,profile:null,isAdmin:false,workspaceUserId:null,impersonating:false,realUserId:null};window.GJ_WORKSPACE_ID=()=>GJ_AUTH.workspaceUserId||GJ_AUTH.profile?.id||null;
const REMEMBER_KEY='gj_login_remember_v1',SESSION_KEY='gj_app_open_session';
const saved=(()=>{try{return JSON.parse(localStorage.getItem(REMEMBER_KEY)||'null')}catch{return null}})();
const WORKSPACE_TABLES=new Set(['customers','planning','app_day_settings','app_absences','fixed_appointments','visit_history','visit_photos']);
function workspaceClient(raw,owner){
 const wrap=(builder,table,needsFilter=true)=>new Proxy(builder,{get(target,prop){
  if(prop==='then'){const q=needsFilter?target.eq('user_id',owner):target;return q.then.bind(q)}
  const value=target[prop];if(typeof value!=='function')return value;
  return (...args)=>{let filter=needsFilter;if(prop==='insert'||prop==='upsert'){const add=row=>({...row,user_id:owner});args[0]=Array.isArray(args[0])?args[0].map(add):add(args[0]);filter=false;if(prop==='upsert'&&table==='app_day_settings'&&args[1]?.onConflict==='datum')args[1]={...args[1],onConflict:'user_id,datum'}}const result=value.apply(target,args);return result&&typeof result.then==='function'?wrap(result,table,filter):result}
 }});
 return new Proxy(raw,{get(target,prop){if(prop==='from')return table=>{const b=target.from(table);return WORKSPACE_TABLES.has(table)?wrap(b,table,true):b};const value=target[prop];return typeof value==='function'?value.bind(target):value}})
}
const lang=localStorage.getItem('gj_app_language')||'nl',TX={nl:['Log in om verder te gaan','E-mailadres','Wachtwoord','E-mailadres onthouden','Inloggen','Wachtwoord vergeten','Alleen het e-mailadres wordt op dit apparaat onthouden. Het wachtwoord wordt nooit opgeslagen.'],en:['Sign in to continue','Email address','Password','Remember email address','Sign in','Forgot password','Only the email address is remembered on this device. The password is never stored.'],de:['Anmelden, um fortzufahren','E-Mail-Adresse','Passwort','E-Mail-Adresse speichern','Anmelden','Passwort vergessen','Auf diesem Gerät wird nur die E-Mail-Adresse gespeichert. Das Passwort wird niemals gespeichert.']},x=TX[lang]||TX.nl;
document.head.insertAdjacentHTML('beforeend',`<style>
#gjAuthGate{position:fixed;inset:0;z-index:999999;background:radial-gradient(circle at 20% 18%,#0b3158 0,#04172e 35%,#020a18 76%);display:flex;align-items:center;justify-content:center;padding:clamp(16px,3vw,44px);font-family:Inter,Arial,sans-serif;color:#eef7ff;overflow:auto}
#gjAuthGate:before{content:'';position:absolute;inset:0;pointer-events:none;opacity:.26;background-image:linear-gradient(rgba(30,130,240,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(30,130,240,.08) 1px,transparent 1px);background-size:42px 42px;mask-image:linear-gradient(to bottom,black,transparent 78%)}
#gjAuthShell{position:relative;width:min(1180px,100%);min-height:650px;display:grid;grid-template-columns:minmax(0,1.08fr) minmax(390px,.92fr);border:1px solid rgba(60,143,230,.28);border-radius:26px;overflow:hidden;background:linear-gradient(135deg,rgba(6,25,49,.94),rgba(2,12,27,.96));box-shadow:0 35px 100px rgba(0,4,15,.65)}
.gjAuthHero{position:relative;padding:64px 56px 120px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;overflow:hidden}.gjAuthHero:before{content:'';position:absolute;width:520px;height:520px;border-radius:50%;background:radial-gradient(circle,rgba(18,156,255,.17),transparent 68%);filter:blur(8px)}
.gjLogo{position:relative;display:block;width:min(470px,82%);height:auto;max-height:390px;object-fit:cover;object-position:50% 27%;border-radius:24px;margin:0 auto 20px;box-shadow:0 22px 55px rgba(0,5,18,.48)}
.gjHeroTitle{position:relative;margin:0;font-size:14px;letter-spacing:.34em;color:#a9bfd8;font-weight:800;text-transform:uppercase}.gjHeroText{position:relative;max-width:520px;color:#8fa7c1;line-height:1.6;margin:18px auto 0;font-size:14px}
#gjAuthCard{align-self:center;width:min(470px,calc(100% - 48px));margin:34px auto;padding:36px;border:1px solid rgba(66,145,226,.25);border-radius:22px;background:linear-gradient(160deg,rgba(8,31,60,.82),rgba(3,17,36,.88));box-shadow:inset 0 1px 0 rgba(255,255,255,.025),0 22px 52px rgba(0,5,15,.28);backdrop-filter:blur(18px)}
.gjWelcome{text-align:center;font-size:24px;font-weight:900;color:#18a4ff;margin-bottom:6px}.gjSub{text-align:center;color:#91a5bd;margin:0 0 26px;font-weight:650}.gjField{display:grid;gap:8px;margin:14px 0;font-weight:800;color:#dceafa;font-size:14px}.gjField input{font:inherit;padding:14px 15px;border:1px solid rgba(86,145,205,.3);border-radius:12px;background:rgba(2,15,33,.72);color:#fff;outline:none;transition:.18s}.gjField input:focus{border-color:#168cf5;box-shadow:0 0 0 3px rgba(22,140,245,.15)}
.gjRemember{display:flex;align-items:center;justify-content:center;gap:9px;margin:16px 0;color:#a9bbcf;font-size:14px;font-weight:700}.gjRemember input{width:18px;height:18px;accent-color:#0789ff}.gjBtn{width:100%;border:1px solid rgba(30,139,255,.6);border-radius:12px;padding:13px;font:inherit;font-weight:900;background:linear-gradient(90deg,#075de8,#078cff);color:#fff;margin-top:10px;box-shadow:0 10px 24px rgba(0,93,230,.22);cursor:pointer}.gjBtn.secondary{background:transparent;color:#a9bfd8;border-color:rgba(100,148,199,.28);box-shadow:none}.gjBtn:hover{filter:brightness(1.08)}.gjMsg{min-height:22px;color:#ff8e8e;margin-top:12px;text-align:center}.gjSecurity{font-size:11px;line-height:1.45;color:#70869f;text-align:center;margin-top:14px}
.gjAuthFooter{position:absolute;left:0;right:0;bottom:0;height:92px;border-top:1px solid rgba(58,137,219,.22);display:flex;align-items:center;justify-content:center;gap:28px;background:rgba(1,8,20,.55)}.gjAuthFooterLogo{height:58px;width:230px;object-fit:cover;border-radius:10px}.gjAuthFooterLogo.planyx{object-position:50% 28%}.gjAuthFooterLogo.gj{object-position:50% 14%}.gjAuthPowered{font-size:10px;letter-spacing:.2em;color:#8298b1;font-weight:800}.gjAuthSep{width:1px;height:52px;background:rgba(102,157,213,.28)}
.gjUserBar{display:none!important}.gjAdminOnly,body:not(.gj-admin) .gjAdminOnly,body:not(.gj-admin) button.gjAdminOnly,body:not(.gj-admin) .menuPanel button.gjAdminOnly{display:none!important}body.gj-admin .gjAdminOnly{display:block!important}body.gj-admin button.gjAdminOnly{display:flex!important}body.gj-admin .menuPanel button.gjAdminOnly{display:grid!important}
@media(max-width:850px){#gjAuthGate{padding:12px}#gjAuthShell{display:block;min-height:auto}.gjAuthHero{display:none}#gjAuthCard{width:auto;margin:16px;padding:26px 20px 130px}.gjAuthFooter{height:104px;gap:12px}.gjAuthFooterLogo{width:128px;height:52px}.gjAuthPowered{font-size:8px}.gjAuthSep{height:42px}}
</style>`);
document.body.insertAdjacentHTML('beforeend',`<div id="gjAuthGate"><div id="gjAuthShell"><section class="gjAuthHero"><img src="planyx-brand.jpeg?v=113900" class="gjLogo" alt="Planyx"><div class="gjHeroTitle">Field operations platform</div><p class="gjHeroText">Planning, routes, customer visits, visit records and reporting in one clear workspace.</p></section><div id="gjAuthCard"><div class="gjWelcome">Welkom terug</div><div class="gjSub">${x[0]}</div><label class="gjField">${x[1]}<input id="gjEmail" type="email" autocomplete="username"></label><label class="gjField">${x[2]}<input id="gjPassword" type="password" autocomplete="current-password"></label><label class="gjRemember"><input id="gjRemember" type="checkbox"> ${x[3]}</label><button id="gjLogin" class="gjBtn">${x[4]}</button><button id="gjReset" class="gjBtn secondary">${x[5]}</button><div id="gjMsg" class="gjMsg"></div><div class="gjSecurity">${x[6]}</div></div><footer class="gjAuthFooter"><img src="planyx-brand.jpeg?v=113900" class="gjAuthFooterLogo planyx" alt="Planyx"><span class="gjAuthSep"></span><span class="gjAuthPowered">POWERED BY</span><img src="gj-motion-brand.png?v=113900" class="gjAuthFooterLogo gj" alt="GJ Motion"></footer></div></div>`);
const emailEl=document.getElementById('gjEmail'),passwordEl=document.getElementById('gjPassword'),rememberEl=document.getElementById('gjRemember'),msg=t=>document.getElementById('gjMsg').textContent=t||'';
if(saved?.remember){emailEl.value=saved.email||'';rememberEl.checked=true;if(saved.password)localStorage.setItem(REMEMBER_KEY,JSON.stringify({remember:true,email:saved.email||''}))}
async function profileFor(user){let {data,error}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;const m=user.user_metadata||{};if(!data){const row={id:user.id,email:user.email,first_name:m.first_name||'',last_name:m.last_name||'',full_name:m.full_name||user.email,role:'user',is_active:true};const r=await sb.from('profiles').upsert(row).select().single();if(r.error)throw r.error;data=r.data}data.role=String(data.role).toLowerCase()==='admin'?'admin':'user';return data}
async function openApp(session){
 const p=await profileFor(session.user);if(p.is_active===false){await sb.auth.signOut();throw new Error('Dit account is uitgeschakeld.')}
 const roleCheck=await sb.rpc('is_app_admin');if(roleCheck.error)throw new Error('De centrale rolcontrole kon niet worden geladen. Voer eerst de v10.7 development-baseline en daarna de v10.8-DEV-SQL uit op het afzonderlijke testproject.');
 const isAdmin=roleCheck.data===true,requested=sessionStorage.getItem('gj_impersonate_user_v102');let wk=p.id,impersonating=false;
 if(isAdmin&&requested&&requested!==p.id){const target=await sb.from('profiles').select('id,is_active').eq('id',requested).maybeSingle();if(!target.error&&target.data&&target.data.is_active!==false){wk=target.data.id;impersonating=true}else sessionStorage.removeItem('gj_impersonate_user_v102')}
 if(!isAdmin&&requested)sessionStorage.removeItem('gj_impersonate_user_v102');
 sessionStorage.setItem('gj_authenticated_user_id',p.id);window.GJ_REAL_USER_ID=p.id;GJ_AUTH.profile=p;GJ_AUTH.isAdmin=isAdmin;GJ_AUTH.realUserId=p.id;GJ_AUTH.workspaceUserId=wk;GJ_AUTH.impersonating=impersonating;GJ_AUTH.identitySb=sb;
 const previousWorkspace=sessionStorage.getItem('gj_workspace_storage_id');GJ_AUTH.sb=workspaceClient(sb,wk);sessionStorage.setItem('gj_workspace_storage_id',wk);if(previousWorkspace!==wk){location.reload();return}
 document.body.classList.toggle('gj-admin',isAdmin);document.getElementById('gjAuthGate').style.display='none';window.dispatchEvent(new CustomEvent('gj-auth-ready',{detail:{profile:p,isAdmin,realUserId:p.id,workspaceUserId:wk,impersonating}}))
}
async function boot(){if(!sb){msg(configurationError?.message||'De developmentconfiguratie kon niet worden geladen.');return}const allowed=sessionStorage.getItem(SESSION_KEY)==='1',r=await sb.auth.getSession();if(allowed&&r.data.session){try{await openApp(r.data.session)}catch(e){msg(e.message)}}else if(r.data.session)await sb.auth.signOut()}
document.getElementById('gjLogin').onclick=async()=>{try{if(!sb)throw configurationError||new Error('Developmentconfiguratie ontbreekt.');msg('Bezig met inloggen...');const email=emailEl.value.trim(),password=passwordEl.value,r=await sb.auth.signInWithPassword({email,password});if(r.error)throw r.error;if(rememberEl.checked)localStorage.setItem(REMEMBER_KEY,JSON.stringify({remember:true,email}));else localStorage.removeItem(REMEMBER_KEY);passwordEl.value='';sessionStorage.setItem(SESSION_KEY,'1');await openApp(r.data.session)}catch(e){msg(e.message)}};
document.getElementById('gjReset').onclick=async()=>{try{if(!sb)throw configurationError||new Error('Developmentconfiguratie ontbreekt.');const email=emailEl.value.trim();if(!email)throw new Error('Vul eerst je e-mailadres in.');const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)throw r.error;msg('Herstellink is verstuurd.')}catch(e){msg(e.message)}};
if(sb)sb.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')window.dispatchEvent(new CustomEvent('gj-auth-signed-out'))});boot();
})();
/* Planning-GJsystems v10.7 */
