/* Planning-GJsystems v10.5 integrated behavior */
(()=>{
 const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const T={
  nl:{profile:'Profiel',changePhoto:'Profielfoto wijzigen',password:'Wachtwoord wijzigen',current:'Huidig wachtwoord',newp:'Nieuw wachtwoord',repeat:'Nieuw wachtwoord herhalen',contact:'Contact',send:'Vraag versturen',refresh:'Vernieuwen',admin:'Beheer',users:'Gebruikers',system:'Systeem',subject:'Onderwerp',question:'Vraag',myMessages:'Mijn berichten',support:'Contact-inbox',all:'Alle statussen',unread:'Alleen ongelezen',search:'Zoek gebruiker, onderwerp of tekst'},
  en:{profile:'Profile',changePhoto:'Change profile photo',password:'Change password',current:'Current password',newp:'New password',repeat:'Repeat new password',contact:'Contact',send:'Send question',refresh:'Refresh',admin:'Admin',users:'Users',system:'System',subject:'Subject',question:'Question',myMessages:'My messages',support:'Support inbox',all:'All statuses',unread:'Unread only',search:'Search user, subject or text'},
  de:{profile:'Profil',changePhoto:'Profilfoto ändern',password:'Passwort ändern',current:'Aktuelles Passwort',newp:'Neues Passwort',repeat:'Neues Passwort wiederholen',contact:'Kontakt',send:'Frage senden',refresh:'Aktualisieren',admin:'Verwaltung',users:'Benutzer',system:'System',subject:'Betreff',question:'Frage',myMessages:'Meine Nachrichten',support:'Support-Posteingang',all:'Alle Status',unread:'Nur ungelesen',search:'Benutzer, Betreff oder Text suchen'}
 };
 let channel=null;
 function uid(){return window.GJ_AUTH?.profile?.id||null} function wid(){return window.GJ_AUTH?.workspaceUserId||uid()} function lang(){return localStorage.getItem('gj_app_language')||'nl'}
 function setVersion(){document.querySelectorAll('.version,.settingsVersion').forEach(e=>e.innerHTML=e.classList.contains('settingsVersion')?'Versie: v10.5<br>Supabase: gekoppeld':'v10.5')}
 async function loadLanguage(){if(!uid())return;try{const {data}=await GJ_AUTH.sb.from('user_app_settings').select('language').eq('user_id',uid()).maybeSingle();const l=data?.language||lang();localStorage.setItem('gj_app_language',l);const s=$('lang');if(s)s.value=l;if(typeof window.setAppLanguage==='function')window.setAppLanguage(l);applyExtraLanguage(l)}catch(e){console.warn('Taal laden',e)}}
 async function saveLanguage(l){if(!uid())return;localStorage.setItem('gj_app_language',l);await GJ_AUTH.sb.from('user_app_settings').upsert({user_id:uid(),language:l,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(typeof window.setAppLanguage==='function')window.setAppLanguage(l);applyExtraLanguage(l)}
 function applyExtraLanguage(l){const x=T[l]||T.nl;document.documentElement.lang=l;const pairs=[['contactSend',x.send],['contactRefresh',x.refresh],['mContactSend',x.send],['mContactRefresh',x.refresh],['v102ChooseProfile',x.changePhoto],['mV102ChooseProfile',x.changePhoto],['v102ChangePassword',x.password],['mV102ChangePassword',x.password]];pairs.forEach(([id,text])=>{if($(id))$(id).textContent=text});}
 function bindLanguage(){const s=$('lang');if(s)s.addEventListener('change',()=>saveLanguage(s.value));document.querySelectorAll('.sidebarLang [data-lang]').forEach(b=>b.addEventListener('click',()=>saveLanguage(b.dataset.lang),true));$('saveSettings')?.addEventListener('click',()=>saveLanguage($('lang')?.value||lang()));}
 function ensureCropBinding(prefix){const choose=$(prefix+'ChooseProfile'),file=$(prefix+'ProfileFile');if(!choose||!file)return;choose.onclick=()=>file.click();file.onchange=e=>{const f=e.target.files?.[0];if(!f)return;const legacy=$('profileFile')||$('desktopProfileFile');if(legacy){const dt=new DataTransfer();dt.items.add(f);legacy.files=dt.files;legacy.dispatchEvent(new Event('change',{bubbles:true}))}else{const r=new FileReader();r.onload=()=>window.dispatchEvent(new CustomEvent('gj-profile-photo-changed',{detail:r.result}));r.readAsDataURL(f)}file.value=''};}
 function lockHeaderPhotos(){['profileButton','desktopProfileButton'].forEach(id=>{const b=$(id);if(b){b.onclick=null;b.style.pointerEvents='none';b.title='Wijzigen via Instellingen → Profiel'}})}
 function addContactFilters(boxId,mobile=false){const box=$(boxId);if(!box||box.previousElementSibling?.classList?.contains('v105ContactToolbar'))return;const bar=document.createElement('div');bar.className='v105ContactToolbar';bar.innerHTML=`<input class="v105ContactSearch" placeholder="${esc((T[lang()]||T.nl).search)}"><select class="v105ContactStatus"><option value="">${esc((T[lang()]||T.nl).all)}</option><option value="nieuw">Nieuw</option><option value="in_behandeling">In behandeling</option><option value="beantwoord">Beantwoord</option><option value="gesloten">Gesloten</option></select><label style="display:flex;flex-direction:row;align-items:center;gap:6px"><input class="v105UnreadOnly" type="checkbox" style="width:auto"> ${(T[lang()]||T.nl).unread}</label><button type="button" class="secondary v105FilterRefresh">↻</button>`;box.before(bar);bar.addEventListener('input',()=>filterCards(box,bar));bar.querySelector('.v105FilterRefresh').onclick=()=>{(mobile?$('mAdminContactRefresh'):$('adminContactRefresh'))?.click()}};
 function filterCards(box,bar){const q=bar.querySelector('.v105ContactSearch').value.toLowerCase(),s=bar.querySelector('.v105ContactStatus').value,u=bar.querySelector('.v105UnreadOnly').checked;box.querySelectorAll('[data-thread-id]').forEach(c=>{const okQ=!q||c.textContent.toLowerCase().includes(q),okS=!s||c.querySelector('select')?.value===s,okU=!u||c.dataset.unread==='true';c.style.display=okQ&&okS&&okU?'':'none'})}
 async function markRead(threadId,reader){if(!uid())return;await GJ_AUTH.sb.from('contact_thread_reads').upsert({thread_id:threadId,user_id:uid(),reader_role:reader,last_read_at:new Date().toISOString()},{onConflict:'thread_id,user_id,reader_role'})}
 function enhanceContactCards(){document.querySelectorAll('[data-thread-id]').forEach(card=>{if(card.dataset.v105)return;card.dataset.v105='1';const status=card.querySelector('select')?.value;card.classList.toggle('v105Closed',status==='gesloten');card.addEventListener('click',()=>markRead(card.dataset.threadId,GJ_AUTH?.isAdmin?'admin':'user'),{once:true});const select=card.querySelector('select');if(select&&!card.querySelector('.v105Reopen')){const b=document.createElement('button');b.type='button';b.className='secondary v105Reopen';b.textContent=status==='gesloten'?'Heropenen':'Afsluiten';b.onclick=()=>{select.value=select.value==='gesloten'?'in_behandeling':'gesloten';card.querySelector('.contactAdminSave,.mContactSave')?.click()};(card.querySelector('.contactActions,.mContactActions')||card).appendChild(b)}})}
 async function setupRealtime(){if(channel)GJ_AUTH.sb.removeChannel(channel);channel=GJ_AUTH.sb.channel('v105-sync-'+uid()).on('postgres_changes',{event:'UPDATE',schema:'public',table:'profiles',filter:'id=eq.'+uid()},payload=>{if(payload.new){GJ_AUTH.profile=payload.new;const admin=String(payload.new.role).toLowerCase()==='admin';if(admin!==GJ_AUTH.isAdmin)location.reload()}}).on('postgres_changes',{event:'*',schema:'public',table:'user_app_settings',filter:'user_id=eq.'+uid()},loadLanguage).on('postgres_changes',{event:'*',schema:'public',table:'contact_threads'},()=>setTimeout(enhanceContactCards,350)).on('postgres_changes',{event:'*',schema:'public',table:'contact_messages'},()=>setTimeout(enhanceContactCards,350)).subscribe()}
 function impersonation(){if(!GJ_AUTH?.impersonating||document.querySelector('.v105Impersonation'))return;document.body.classList.add('v105Impersonating');const bar=document.createElement('div');bar.className='v105Impersonation';bar.innerHTML=`Voordoen als gebruiker <button type="button">Terug naar beheer</button>`;bar.querySelector('button').onclick=()=>{sessionStorage.removeItem('gj_impersonate_user_v102');sessionStorage.removeItem('gj_workspace_storage_id');location.reload()};document.body.prepend(bar)}
 window.addEventListener('gj-auth-ready',async()=>{setVersion();lockHeaderPhotos();ensureCropBinding('v102');ensureCropBinding('mV102');bindLanguage();await loadLanguage();addContactFilters('adminContactInbox');addContactFilters('mAdminContactInbox',true);impersonation();setupRealtime();setInterval(enhanceContactCards,800);document.querySelectorAll('.gjAdminOnly').forEach(e=>{if(GJ_AUTH.isAdmin)e.style.removeProperty('display')})});
})();
