/* Planning-GJsystems v10.7 integrated cross-device module. */
(()=>{
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const auth=()=>window.GJ_AUTH,uid=()=>auth()?.profile?.id,wid=()=>auth()?.workspaceUserId||uid(),sb=()=>auth()?.sb;
 const lang=()=>localStorage.getItem('gj_app_language')||'nl';
 const words={nl:{manage:'Gegevens beheren',help:'Beheer alleen de gegevens van deze werkruimte. Voor verwijderen moet je exact BEVESTIG typen.',planning:'Planning legen',fixed:'Vaste afspraken legen',unplanned:'Niet ingepland legen',history:'Historie legen',routes:'Routecache legen',backup:'Back-up downloaden',restore:'Back-up herstellen',database:'Database legen',all:'Alles resetten',attach:'Bijlage toevoegen',reply:'Antwoorden',done:'Actie voltooid.'},en:{manage:'Manage data',help:'Manage only this workspace. Type BEVESTIG exactly before deleting.',planning:'Clear planning',fixed:'Clear fixed appointments',unplanned:'Clear unplanned',history:'Clear history',routes:'Clear route cache',backup:'Download backup',restore:'Restore backup',database:'Clear database',all:'Reset everything',attach:'Add attachment',reply:'Reply',done:'Action completed.'},de:{manage:'Daten verwalten',help:'Verwalte nur diesen Arbeitsbereich. Zum Löschen exakt BEVESTIG eingeben.',planning:'Planung leeren',fixed:'Feste Termine leeren',unplanned:'Ungeplante leeren',history:'Verlauf leeren',routes:'Routencache leeren',backup:'Backup herunterladen',restore:'Backup wiederherstellen',database:'Datenbank leeren',all:'Alles zurücksetzen',attach:'Anhang hinzufügen',reply:'Antworten',done:'Aktion abgeschlossen.'}};
 const w=()=>words[lang()]||words.nl;
 window.renderOverview=function(){const list=$('overviewList');if(!list)return;let data={customers:[],visits:[]};try{data=JSON.parse(localStorage.getItem(localKey())||'null')||data}catch(_){ }const q=String($('search')?.value||'').toLowerCase();const rows=(data.customers||[]).filter(c=>!q||[c.name,c.chain,c.city,c.postal].some(v=>String(v||'').toLowerCase().includes(q)));list.innerHTML=rows.length?rows.map(c=>{const visits=(data.visits||[]).filter(v=>String(v.customerId)===String(c.id)&&v.status!=='Uit planning').sort((a,b)=>String(a.date).localeCompare(String(b.date))),next=visits.find(v=>v.date>=new Date().toISOString().slice(0,10));return `<div class="card"><strong>${esc(c.name||'Klant')}</strong><div class="muted">${esc([c.city,c.postal].filter(Boolean).join(' · '))}</div><div>${next?esc(next.date+' · '+(next.status||'Gepland')):'Niet ingepland'}</div></div>`}).join(''):'<div class="card empty">Geen klanten gevonden.</div>'};
 function setVersion(){document.title=document.title.replace(/v10\.5/g,'v10.6');document.querySelectorAll('.version,.productVersion,.settingsVersion').forEach(e=>e.innerHTML=e.innerHTML.replace(/v10\.5|v9\.0/g,'v10.6'))}
 function enforceRole(){const admin=auth()?.isAdmin===true;document.body.classList.toggle('gj-admin',admin);document.querySelectorAll('.gjAdminOnly').forEach(e=>{e.style.display=admin?'':'none'});if(!admin){document.querySelector('#admin.active,#adminMobile.active')?.classList.remove('active')}}
 function maintenancePanel(){
   const settings=$('settings');if(!settings||settings.querySelector('.v106Maintenance'))return;
   const x=w(),box=document.createElement('section');box.className='v106Maintenance panel settingsBlock';box.innerHTML=`<h3>${x.manage}</h3><p class="muted">${x.help}</p><div class="v106MaintenanceGrid">${[['planning',x.planning],['fixed',x.fixed],['unplanned',x.unplanned],['history',x.history],['routes',x.routes],['backup',x.backup],['restore',x.restore],['database',x.database],['all',x.all]].map(([a,l])=>`<button type="button" data-v106-maint="${a}">${l}</button>`).join('')}</div><input class="v106RestoreFile" type="file" accept="application/json" hidden><div class="v106MaintenanceStatus adminStatus"></div>`;settings.appendChild(box)
 }
 function enhanceUsers(){document.querySelectorAll('#adminUsersTable tbody tr,.adminUser').forEach(row=>{const id=row.querySelector('[data-id]')?.dataset.id||row.dataset.id;if(!id)return;const box=row.querySelector('.adminUserActions')||row.lastElementChild||row;if(!box.querySelector('.v106EditUser')){const b=document.createElement('button');b.type='button';b.className='v106EditUser';b.dataset.id=id;b.textContent='Bewerken';box.appendChild(b)}if(id!==uid()&&!box.querySelector('.v106Impersonate')){const b=document.createElement('button');b.type='button';b.className='v106Impersonate';b.dataset.id=id;b.textContent='Voordoen als gebruiker';box.appendChild(b)}})}
 document.addEventListener('click',async e=>{const as=e.target.closest('.v106Impersonate');if(as){sessionStorage.setItem('gj_impersonate_user_v102',as.dataset.id);sessionStorage.removeItem('gj_workspace_storage_id');location.reload();return}const edit=e.target.closest('.v106EditUser');if(!edit)return;const row=edit.closest('tr,.adminUser'),name=row?.querySelector('strong,td')?.textContent?.trim()||'',parts=name.split(/\s+/),first=prompt('Voornaam',parts.shift()||'');if(first===null)return;const last=prompt('Achternaam',parts.join(' '));if(last===null)return;const full=[first.trim(),last.trim()].filter(Boolean).join(' ');const r=await sb().from('profiles').update({first_name:first.trim(),last_name:last.trim(),full_name:full,updated_at:new Date().toISOString()}).eq('id',edit.dataset.id);if(r.error)alert(r.error.message);else{$('btnAdminRefreshUsers')?.click();$('mAdminRefreshUsers')?.click()} });
 function localKey(){return document.body.querySelector('#calendarBody')?'bp_pro_v2_'+(sessionStorage.getItem('gj_workspace_storage_id')||'guest'):'gj_mobile_v56_data_'+(sessionStorage.getItem('gj_workspace_storage_id')||'guest')}
 async function backup(){const tables=['customers','planning','app_day_settings','app_absences'],out={version:'10.6',workspace_id:wid(),created_at:new Date().toISOString(),tables:{}};for(const t of tables){const r=await sb().from(t).select('*').eq('user_id',wid());if(r.error)throw r.error;out.tables[t]=r.data||[]}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='Planning-GJsystems-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
 async function clear(action,status){if(action==='backup'){await backup();status.textContent='Back-up gemaakt.';return}if(action==='restore'){status.textContent='Kies het back-upbestand.';status.closest('.v106Maintenance').querySelector('.v106RestoreFile').click();return}if(action!=='routes'&&prompt('Typ exact BEVESTIG om door te gaan:')!=='BEVESTIG')return;status.textContent='Bezig…';window.__GJ_WORKSPACE_CLEARING__=true;if(action==='routes'){Object.keys(localStorage).filter(k=>/route|tomtom|geocode/i.test(k)).forEach(k=>localStorage.removeItem(k))}else{const r=await sb().rpc('clear_workspace_data',{p_workspace_id:wid(),p_action:action});if(r.error){window.__GJ_WORKSPACE_CLEARING__=false;throw r.error}}if(['planning','fixed','unplanned','history','database','all'].includes(action)){try{localStorage.removeItem(localKey())}catch(_){}}status.textContent=w().done;location.reload()}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-v106-maint]');if(!b)return;try{b.disabled=true;await clear(b.dataset.v106Maint,b.closest('.v106Maintenance').querySelector('.v106MaintenanceStatus'))}catch(err){alert(err.message)}finally{b.disabled=false}});
 document.addEventListener('change',async e=>{if(!e.target.matches('.v106RestoreFile'))return;const file=e.target.files?.[0],status=e.target.closest('.v106Maintenance').querySelector('.v106MaintenanceStatus');if(!file)return;try{if(prompt('Typ exact BEVESTIG om deze back-up terug te zetten:')!=='BEVESTIG')return;const data=JSON.parse(await file.text());if(!data?.tables)throw new Error('Ongeldig back-upbestand.');status.textContent='Back-up wordt hersteld…';for(const table of ['customers','planning','app_day_settings','app_absences']){const rows=(data.tables[table]||[]).map(r=>({...r,user_id:wid()}));if(!rows.length)continue;const options=table==='app_day_settings'?{onConflict:'user_id,datum'}:undefined;for(let i=0;i<rows.length;i+=200){const q=options?sb().from(table).upsert(rows.slice(i,i+200),options):sb().from(table).upsert(rows.slice(i,i+200));const r=await q;if(r.error)throw r.error}}status.textContent='Back-up is hersteld.';setTimeout(()=>location.reload(),650)}catch(err){status.textContent=err.message}finally{e.target.value=''}});
 async function uploadFiles(threadId,messageId,files){for(const file of [...files||[]]){if(file.size>10485760)throw new Error(file.name+' is groter dan 10 MB.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=threadId+'/'+crypto.randomUUID()+'-'+safe;const up=await sb().storage.from('contact-attachments').upload(path,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(up.error)throw up.error;const ins=await sb().from('contact_attachments').insert({thread_id:threadId,message_id:messageId||null,uploader_id:uid(),file_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size});if(ins.error)throw ins.error}}
 function contactInputs(){[['contactMessage','contactSend','contactAttachment'],['mContactMessage','mContactSend','mContactAttachment']].forEach(([m,b,id])=>{const msg=$(m),btn=$(b);if(!msg||!btn||$(id))return;const f=document.createElement('input');f.id=id;f.className='v106NewAttachment';f.type='file';f.multiple=true;f.accept='image/*,.pdf,.txt,.docx,.xlsx';msg.closest('label')?.after(f)})}
 document.addEventListener('click',async e=>{const send=e.target.closest('#contactSend,#mContactSend');if(!send)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const mobile=send.id==='mContactSend',message=$(mobile?'mContactMessage':'contactMessage'),subject=$(mobile?'mContactSubject':'contactSubject'),files=$(mobile?'mContactAttachment':'contactAttachment'),status=$(mobile?'mContactStatus':'contactStatus');const text=message.value.trim();if(text.length<3){status.textContent='Vul een duidelijke vraag in.';return}try{send.disabled=true;status.textContent='Wordt verstuurd…';const r=await sb().rpc('create_contact_thread',{p_subject:subject.value,p_message:text});if(r.error)throw r.error;await uploadFiles(r.data,null,files.files);message.value='';files.value='';status.textContent='Je bericht is verstuurd.';setTimeout(()=>location.reload(),500)}catch(err){status.textContent=err.message}finally{send.disabled=false}},true);
 async function enhanceThread(card){if(card.dataset.v106==='1')return;const thread=card.dataset.threadId;if(!thread)return;card.dataset.v106='1';card.querySelectorAll(':scope>.v106AttachmentList,:scope>.v106Reply').forEach(e=>e.remove());const list=document.createElement('div');list.className='v106AttachmentList';card.appendChild(list);const r=await sb().from('contact_attachments').select('*').eq('thread_id',thread).order('created_at');if(!r.error)for(const a of r.data||[]){const row=document.createElement('div');row.className='v106Attachment';row.innerHTML=`<span>📎</span><button type="button" class="secondary v106OpenAttachment" data-path="${esc(a.storage_path)}">${esc(a.file_name)}</button>`;list.appendChild(row)}const reply=document.createElement('div');reply.className='v106Reply';reply.innerHTML=`<textarea placeholder="${w().reply}"></textarea><div><input type="file" multiple accept="image/*,.pdf,.txt,.docx,.xlsx"><button type="button" data-v106-reply="${thread}">${w().reply}</button></div>`;card.appendChild(reply)}
 async function enhanceThreads(){for(const c of document.querySelectorAll('[data-thread-id]'))try{await enhanceThread(c)}catch(e){console.warn(e)}}
 async function updateNotifications(){if(!uid())return;const role=auth().isAdmin?'admin':'user';let tq=sb().from('contact_threads').select('id,user_id,updated_at,contact_messages(sender_role,created_at)');if(!auth().isAdmin)tq=tq.eq('user_id',uid());const [tr,rr]=await Promise.all([tq,sb().from('contact_thread_reads').select('thread_id,last_read_at').eq('user_id',uid()).eq('reader_role',role)]);if(tr.error||rr.error)return;const reads=new Map((rr.data||[]).map(r=>[r.thread_id,new Date(r.last_read_at).getTime()])),unreadIds=new Set();for(const t of tr.data||[]){const incoming=(t.contact_messages||[]).filter(m=>m.sender_role!==role).map(m=>new Date(m.created_at).getTime());if(incoming.length&&Math.max(...incoming)>(reads.get(t.id)||0))unreadIds.add(t.id)}const unread=unreadIds.size;document.querySelectorAll('[data-thread-id]').forEach(c=>c.dataset.unread=unreadIds.has(c.dataset.threadId)?'true':'false');for(const id of ['adminContactBadge','mAdminContactBadge'])if($(id))$(id).innerHTML=unread?`<span class="v106Unread">${unread}</span>`:'';for(const selector of ['button[data-screen="contactMobile"]','.nav[data-screen="contact"]']){const b=document.querySelector(selector);if(b){let badge=b.querySelector('.v106Unread');if(unread&&!badge){badge=document.createElement('span');badge.className='v106Unread';b.appendChild(badge)}if(badge){badge.textContent=unread;badge.style.display=unread?'inline-grid':'none'}}}}
 document.addEventListener('click',async e=>{const o=e.target.closest('.v106OpenAttachment');if(o){const r=await sb().storage.from('contact-attachments').createSignedUrl(o.dataset.path,60);if(r.error)alert(r.error.message);else window.open(r.data.signedUrl,'_blank');return}const b=e.target.closest('[data-v106-reply]');if(!b)return;const box=b.closest('.v106Reply'),text=box.querySelector('textarea').value.trim(),files=box.querySelector('input').files;if(!text&&!files.length)return;try{b.disabled=true;let mid=null;const role=auth().isAdmin?'admin':'user';if(text){const r=await sb().from('contact_messages').insert({thread_id:b.dataset.v106Reply,sender_id:uid(),sender_role:role,message:text}).select('id').single();if(r.error)throw r.error;mid=r.data.id}await uploadFiles(b.dataset.v106Reply,mid,files);const u=await sb().from('contact_threads').update({status:role==='admin'?'beantwoord':'in_behandeling',updated_at:new Date().toISOString(),closed_at:null}).eq('id',b.dataset.v106Reply);if(u.error)throw u.error;location.reload()}catch(err){alert(err.message)}finally{b.disabled=false}});
 document.addEventListener('click',e=>{if(e.target.closest('[data-thread-id]'))setTimeout(updateNotifications,500)});
 let realtime=null;
 function start(){setVersion();enforceRole();maintenancePanel();contactInputs();enhanceThreads();enhanceUsers();updateNotifications();if(!document.body.dataset.v106Observed){document.body.dataset.v106Observed='1';new MutationObserver(()=>{enhanceThreads();enhanceUsers()}).observe(document.body,{subtree:true,childList:true})}if(!realtime){realtime=sb().channel('v106-contact-'+uid()).on('postgres_changes',{event:'*',schema:'public',table:'contact_threads'},updateNotifications).on('postgres_changes',{event:'*',schema:'public',table:'contact_messages'},updateNotifications).on('postgres_changes',{event:'*',schema:'public',table:'contact_attachments'},()=>{updateNotifications();document.querySelectorAll('[data-thread-id]').forEach(c=>delete c.dataset.v106);enhanceThreads()}).subscribe()}}
 window.addEventListener('gj-auth-ready',start);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(auth()?.profile)start()});else if(auth()?.profile)start();window.addEventListener('load',()=>{if(auth()?.profile)start()});
})();
